services:
  backend:
    build: .
    container_name: segarkosan-backend
    restart: unless-stopped
    expose:
      - "8080:5000"

  nginx:
    image: nginx:alpine
    container_name: segarkosan-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
