services:
  backend:
    build: .
    container_name: segarkosan-backend
    restart: unless-stopped
    # --- TAMBAHKAN BAGIAN INI ---
    env_file:
      - .env
    # ----------------------------
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: segarkosan-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Pastikan file konfigurasi Nginx Anda ada di folder host ./nginx/conf.d/
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - infra_net

networks:
  infra_net:
    external: true
